builds:
  - goos:
      - linux
    goarch:
      - amd64
      - arm
    ldflags:
      - -s -w

checksum:
  disable: true

changelog:
  filters:
    exclude:
      - '^Merge pull request'

nfpms:
  - id: ccdns
    vendor: The VitalVas
    homepage: https://github.com/vitalvas/ccdns
    package_name: ccdns
    description: Customized CoreDNS Server
    maintainer: The VitalVas <source@vitalvas.com>
    license: MIT
    formats:
      - deb
    contents:
      - src: tools/ccdns.service
        dst: /lib/systemd/system/ccdns.service
        file_info:
          mode: 0644
      - dst: /etc/ccdns
        type: dir
        file_info:
          mode: 0755
      - src: example/config/default.conf
        dst: /etc/ccdns/ccdns.conf
        type: config|noreplace
        file_info:
          mode: 0644
